# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: New release

concurrency:
  group: build
  cancel-in-progress: true

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  DOTNET_VERSION: '8.0.201'
  NEXUSMOD_API_KEY: ${{ secrets.NEXUSMODS_API_KEY }}
  NEXUSMOD_COOKIE_SID_DEVELOP: ${{ secrets.NEXUSMODS_SESSION_COOKIE }}
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore packages
        run: nuget restore ./WitchyBND.sln -LockedMode

      - name: Build
        run: dotnet build -c Release --no-restore ./WitchyTests/WitchyTests.csproj # Builds WitchyBND which builds Shell

      - name: Install test runner
        run: nuget install NUnit.ConsoleRunner -Version 3.17.0 -DirectDownload -OutputDirectory .

      - name: Run unit tests
        run: ./NUnit.ConsoleRunner.3.17.0/tools/nunit3-console.exe  ./WitchyTests/bin/Release/net8.0-windows/WitchyTests.dll --where "cat != SkipOnGitHubAction"

      - name: Publish application
        run: |
          cd WitchyBND
          dotnet publish -c Release --no-restore

      - name: Archive release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: '../../WitchyBND-${{ github.ref_name }}.zip'
          directory: './bin/publish'
          path: '.'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'WitchyBND-SHA${{ github.sha }}'
          path: WitchyBND-${{ github.ref_name }}.zip

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: 'WitchyBND-SHA${{ github.sha }}'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'WitchyBND-${{ github.ref_name }}.zip'
          bodyFile: "./NOTES.md"
          token: ${{ secrets.GITHUB_TOKEN }}

  nexus:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: 'WitchyBND-SHA${{ github.sha }}'

      - name: Setup mod uploader
        run: dotnet tool install -g Digitalroot.ModUploader

      - name: Check mod uploader
        run: drmu nx check

      - name: Upload to Elden Ring Nexus
        run: drmu nexusmods upload
          -f "WitchyBND"
          -v "${{ github.ref_name }}"
          -t Main
          -d "For the list of changes, view the changelog [url=https://github.com/ividyon/WitchyBND]on the GitHub page[/url]."
          -g eldenring
          -ddwm
          3862 "WitchyBND-${{ github.ref_name }}.zip"

      - name: Upload to ACVI Nexus
        run: drmu nexusmods upload
          -f "WitchyBND"
          -v "${{ github.ref_name }}"
          -t Main
          -d "For the list of changes, view the changelog [url=https://github.com/ividyon/WitchyBND]on the GitHub page[/url]."
          -g armoredcore6firesofrubicon
          -ddwm
          20 "WitchyBND-${{ github.ref_name }}.zip"

      - name: Upload to DS1 Nexus
        run: drmu nexusmods upload
          -f "WitchyBND"
          -v "${{ github.ref_name }}"
          -t Main
          -d "For the list of changes, view the changelog [url=https://github.com/ividyon/WitchyBND]on the GitHub page[/url]."
          -g darksouls
          -ddwm
          1865 "WitchyBND-${{ github.ref_name }}.zip"

      - name: Upload to DS1R Nexus
        run: drmu nexusmods upload
          -f "WitchyBND"
          -v "${{ github.ref_name }}"
          -t Main
          -d "For the list of changes, view the changelog [url=https://github.com/ividyon/WitchyBND]on the GitHub page[/url]."
          -g darksoulsremastered
          -ddwm
          653 "WitchyBND-${{ github.ref_name }}.zip"

      - name: Upload to DS2 Nexus
        run: drmu nexusmods upload
          -f "WitchyBND"
          -v "${{ github.ref_name }}"
          -t Main
          -d "For the list of changes, view the changelog [url=https://github.com/ividyon/WitchyBND]on the GitHub page[/url]."
          -g darksouls2
          -ddwm
          1192 "WitchyBND-${{ github.ref_name }}.zip"

      - name: Upload to DS3 Nexus
        run: drmu nexusmods upload
          -f "WitchyBND"
          -v "${{ github.ref_name }}"
          -t Main
          -d "For the list of changes, view the changelog [url=https://github.com/ividyon/WitchyBND]on the GitHub page[/url]."
          -g darksouls3
          -ddwm
          1676 "WitchyBND-${{ github.ref_name }}.zip"

      - name: Upload to Sekiro Nexus
        run: drmu nexusmods upload
          -f "WitchyBND"
          -v "${{ github.ref_name }}"
          -t Main
          -d "For the list of changes, view the changelog [url=https://github.com/ividyon/WitchyBND]on the GitHub page[/url]."
          -g sekiro
          -ddwm
          1633 "WitchyBND-${{ github.ref_name }}.zip"

      - name: Upload to Bloodborne Nexus
        run: drmu nexusmods upload
          -f "WitchyBND"
          -v "${{ github.ref_name }}"
          -t Main
          -d "For the list of changes, view the changelog [url=https://github.com/ividyon/WitchyBND]on the GitHub page[/url]."
          -g bloodborne
          -ddwm
          20 "WitchyBND-${{ github.ref_name }}.zip"